import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import {
  AlertTriangle, Archive, BookOpen, Bot, Bug, Check, ChevronDown, ChevronLeft,
  ChevronRight, ClipboardCheck, Copy, Database, Download, FileBarChart, FileText,
  GitBranch, Home, Layers3, ListChecks, Loader2, Menu, PanelLeftClose, Play,
  Plus, RefreshCw, RotateCcw, Search, Settings, Sparkles, SquareTerminal, X
} from 'lucide-react';
import * as XLSX from 'xlsx';
import { jsPDF } from 'jspdf';
import './styles.css';

type Row = Record<string, any>;
type PageKey = 'dashboard'|'quick'|'cases'|'bug'|'logs'|'sql'|'regression'|'reports'|'knowledge'|'workflows'|'settings';
type Drawer = { type: string; item: Row } | null;

const NAV: {id:PageKey;label:string;icon:React.ReactNode}[] = [
  {id:'dashboard',label:'工作台首页',icon:<Home/>},{id:'quick',label:'快捷任务',icon:<Sparkles/>},
  {id:'cases',label:'用例库',icon:<ListChecks/>},{id:'bug',label:'Bug 分析',icon:<Bug/>},
  {id:'logs',label:'日志分析',icon:<SquareTerminal/>},{id:'sql',label:'SQL 分析',icon:<Database/>},
  {id:'regression',label:'回归测试',icon:<ClipboardCheck/>},{id:'reports',label:'测试报告',icon:<FileBarChart/>},
  {id:'knowledge',label:'知识库',icon:<BookOpen/>},{id:'workflows',label:'全链路任务',icon:<GitBranch/>},
  {id:'settings',label:'配置中心',icon:<Settings/>}
];
const TASK_META:Record<string,{title:string;desc:string;hint:string;required:string[]}> = {
  cases:{title:'生成测试用例',desc:'将需求拆解为可执行用例',hint:'粘贴需求背景、业务规则、验收标准和异常场景…',required:['需求背景','验收标准']},
  bug:{title:'Bug 分析',desc:'定位现象、证据和回归范围',hint:'粘贴 Bug 现象、复现步骤、实际/预期结果、相关改动…',required:['问题现象','复现步骤','预期结果']},
  logs:{title:'日志分析',desc:'还原调用链与异常节点',hint:'粘贴发生时间、环境、traceId、上下文日志和预期行为…',required:['发生时间或 traceId','日志上下文']},
  sql:{title:'SQL 分析',desc:'检查正确性、性能和一致性',hint:'粘贴 SQL、表结构、执行计划、实际结果和预期结果…',required:['SQL 语句','分析目标']},
  regression:{title:'生成回归清单',desc:'从改动与历史风险生成范围',hint:'描述版本改动、影响模块、关联 Bug 和测试范围…',required:['版本改动','影响模块']},
  report:{title:'生成测试报告',desc:'汇总多来源形成质量结论',hint:'描述发布版本、测试范围、执行情况和遗留风险…',required:['发布版本','测试范围']}
};
const KB_CATEGORIES=['历史 Bug 库','业务规则库','接口异常库','日志规律库','SQL 经验库','压测经验库','回归规则库'];
const API={
  async request(path:string,options?:RequestInit){const res=await fetch(`/api${path}`,{headers:{'Content-Type':'application/json',...(options?.headers||{})},...options});const data=await res.json();if(!res.ok)throw Object.assign(new Error(data.error||'请求失败'),{data});return data;},
  list(resource:string,params:Record<string,string|number|undefined>={}){const q=new URLSearchParams(Object.entries(params).filter(([,v])=>v!==undefined&&v!=='').map(([k,v])=>[k,String(v)]));return this.request(`/${resource}?${q}`);},
  get(resource:string,id:string){return this.request(`/${resource}/${id}`);},
  post(resource:string,data:Row){return this.request(`/${resource}`,{method:'POST',body:JSON.stringify(data)});},
  patch(resource:string,id:string,data:Row){return this.request(`/${resource}/${id}`,{method:'PATCH',body:JSON.stringify(data)});}
};

function App(){
  const [page,setPage]=useState<PageKey>('dashboard');
  const [bootstrap,setBootstrap]=useState<Row|null>(null);
  const [drawer,setDrawer]=useState<Drawer>(null);
  const [toast,setToast]=useState('');
  const [collapsed,setCollapsed]=useState(false);
  const [migrate,setMigrate]=useState<Row|null>(null);
  const refresh=async()=>setBootstrap(await API.request('/bootstrap'));
  useEffect(()=>{refresh().catch(e=>setToast(e.message));const raw=localStorage.getItem('testpilot-personal-workbench-v1');if(raw){try{setMigrate(JSON.parse(raw));}catch{/* ignore */}}},[]);
  useEffect(()=>{if(!toast)return;const timer=setTimeout(()=>setToast(''),2800);return()=>clearTimeout(timer)},[toast]);
  if(!bootstrap)return <div className="loading"><Loader2 className="spin"/><span>正在准备个人工作台…</span></div>;
  const props={bootstrap,refresh,setPage,setDrawer,notify:setToast};
  return <div className={`shell ${collapsed?'is-collapsed':''}`}>
    <aside className="sidebar">
      <div className="brand"><div className="brand-mark">T</div><div className="brand-copy"><strong>TestPilot</strong><small>PERSONAL QA WORKSPACE</small></div></div>
      <button className="collapse" onClick={()=>setCollapsed(v=>!v)} aria-label="收起侧栏">{collapsed?<Menu/>:<PanelLeftClose/>}</button>
      <nav>{NAV.map((item,index)=><button key={item.id} className={page===item.id?'active':''} onClick={()=>setPage(item.id)} title={item.label}><span className="nav-icon">{item.icon}</span><span className="nav-num">{String(index+1).padStart(2,'0')}</span><span className="nav-text">{item.label}</span></button>)}</nav>
      <div className="side-status"><i/><span>本机数据库已连接<br/><small>127.0.0.1:3344</small></span></div>
    </aside>
    <main className="main">
      <header className="topbar"><div><span className="eyebrow">PERSONAL WORKSPACE</span><h1>{NAV.find(n=>n.id===page)?.label}</h1></div><div className="top-actions"><button className="button subtle" onClick={()=>setPage('knowledge')}><BookOpen/>维护知识</button><button className="button primary" onClick={()=>setPage('quick')}><Plus/>新建任务</button></div></header>
      <div className="content">
        {page==='dashboard'&&<Dashboard {...props}/>} {page==='quick'&&<QuickTasks {...props}/>} {page==='cases'&&<CasesPage {...props}/>} 
        {['bug','logs','sql'].includes(page)&&<AnalysisPage {...props} taskType={page}/>} {page==='regression'&&<RegressionPage {...props}/>} 
        {page==='reports'&&<ReportsPage {...props}/>} {page==='knowledge'&&<KnowledgePage {...props}/>} {page==='workflows'&&<WorkflowPage {...props}/>} {page==='settings'&&<SettingsPage {...props}/>} 
      </div>
    </main>
    {drawer&&<DetailDrawer drawer={drawer} close={()=>setDrawer(null)} {...props}/>} 
    {toast&&<div className="toast"><Check/>{toast}</div>}
    {migrate&&<MigrationModal data={migrate} close={()=>setMigrate(null)} done={()=>{localStorage.removeItem('testpilot-personal-workbench-v1');setMigrate(null);refresh();}} notify={setToast}/>} 
  </div>;
}

function Dashboard({bootstrap,setPage,setDrawer}:any){
  const [recent,setRecent]=useState<Row[]>([]);useEffect(()=>{API.list('tasks',{pageSize:20}).then(r=>setRecent(r.items.slice(0,5)))},[]);
  const metrics=[['待补充',2,'缺少必要信息','warn'],['待审核',recent.filter(i=>i.reviewStatus==='待审核').length,'需要人工确认','yellow'],['执行中',1,'回归与全链路','blue'],['阻塞',1,'需要优先处理','red'],['高风险',recent.filter(i=>i.risk==='P0').length,'P0 任务与用例','red'],['不可上线',0,'当前质量结论','dark']];
  return <div className="page stack">
    <section className="hero"><div><span className="kicker">GOOD MORNING · QA</span><h2>今天从哪里开始？</h2><p>任务、用例、知识与质量结论都在一个工作台内完成。</p></div><button className="button dark" onClick={()=>setPage('quick')}><Sparkles/>创建智能任务</button></section>
    <div className="metric-grid six">{metrics.map(([l,v,d,c])=><article className={`metric ${c}`} key={String(l)}><span>{l}</span><strong>{v}</strong><small>{d}</small></article>)}</div>
    <div className="two-col wide-left"><section className="panel"><PanelTitle title="快捷入口" hint="每项任务都内置智能输入" action={<button className="text-button" onClick={()=>setPage('quick')}>查看全部 <ChevronRight/></button>}/><div className="quick-grid">{Object.entries(TASK_META).map(([id,m])=><button key={id} className="quick-card" onClick={()=>setPage((id==='report'?'reports':id==='regression'?'regression':id==='cases'?'cases':id) as PageKey)}><TaskIcon type={id}/><div><strong>{m.title}</strong><span>{m.desc}</span></div><ChevronRight/></button>)}</div></section>
      <section className="panel"><PanelTitle title="数据资产" hint="SQLite 实时统计"/><div className="asset-list"><Asset label="测试用例" value={bootstrap.counts.cases} onClick={()=>setPage('cases')}/><Asset label="任务记录" value={bootstrap.counts.tasks} onClick={()=>setPage('bug')}/><Asset label="知识条目" value={bootstrap.counts.knowledge} onClick={()=>setPage('knowledge')}/><Asset label="测试报告" value={bootstrap.counts.reports} onClick={()=>setPage('reports')}/></div></section></div>
    <section className="panel"><PanelTitle title="最近任务" hint="点击查看详情"/><div className="table-wrap"><table><thead><tr><th>任务</th><th>类型</th><th>模块</th><th>风险</th><th>审核</th><th>更新时间</th></tr></thead><tbody>{recent.map(t=><tr key={t.id} onClick={()=>setDrawer({type:'task',item:t})}><td><strong>{t.title}</strong><small className="id">{t.id}</small></td><td>{TASK_META[t.type]?.title}</td><td>{shortModule(t.moduleLabel)}</td><td><Badge value={t.risk}/></td><td><Badge value={t.reviewStatus}/></td><td>{date(t.updatedAt)}</td></tr>)}</tbody></table></div></section>
  </div>;
}

function QuickTasks({bootstrap,refresh,notify,setDrawer}:any){
  const [selected,setSelected]=useState<string[]>(['bug']);const [text,setText]=useState('');const [moduleId,setModuleId]=useState(bootstrap.modules[0]?.id||'');const [running,setRunning]=useState(false);
  const missing=useMemo(()=>{const req=[...new Set(selected.flatMap(x=>TASK_META[x].required))];return text.trim().length>30?[]:req},[selected,text]);
  async function create(){if(!text.trim()){notify('请先输入任务信息');return}setRunning(true);try{const parent=selected.length>1?await API.post('tasks',{type:'combination',title:`组合任务 · ${selected.map(x=>TASK_META[x].title).join(' + ')}`,moduleId,status:'执行中',input:{text,steps:selected},result:{progress:0}}):null;const created=[];for(const type of selected){const result=localAnalysis(type,text);created.push(await API.post('tasks',{type,title:guessTitle(text,TASK_META[type].title),moduleId,parentId:parent?.id,status:'待审核',risk:result.risk,input:{text},result}));}await refresh();notify(`已创建 ${created.length} 个${selected.length>1?'子':''}任务`);setDrawer({type:'task',item:created[0]});setText('');}catch(e:any){notify(e.message)}finally{setRunning(false)}}
  return <div className="page stack"><PageIntro title="快速创建任务" desc="勾选单项或组合任务，共享上下文并自动拆解为独立子任务。"/>
    <div className="task-selector">{Object.entries(TASK_META).map(([id,m])=><button key={id} className={selected.includes(id)?'selected':''} onClick={()=>setSelected(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id])}><span className="check">{selected.includes(id)&&<Check/>}</span><TaskIcon type={id}/><strong>{m.title}</strong><small>{m.desc}</small></button>)}</div>
    <div className="two-col"><section className="panel smart-panel"><PanelTitle title="智能输入" hint="文本一次输入，按任务模板分别判断"/><label>项目 / 模块 / 子模块</label><ModuleSelect modules={bootstrap.modules} value={moduleId} onChange={setModuleId}/><label>完整上下文</label><textarea value={text} onChange={e=>setText(e.target.value)} placeholder={selected.map(s=>TASK_META[s].hint).join('\n')}/><div className="smart-actions"><button className="button primary" onClick={create} disabled={!selected.length||running}>{running?<Loader2 className="spin"/>:<Sparkles/>}检查信息并创建任务</button><button className="button" onClick={()=>setText('支付成功后订单状态没有同步。环境 staging，版本 v2.8.3，复现步骤：完成支付后等待 30 秒查询订单仍为待支付；预期订单应为已支付。traceId=demo-1024，日志显示消费事务回滚。')}>载入示例</button></div></section>
      <aside className="panel"><PanelTitle title="创建前检查" hint={`${selected.length} 个任务 · ${missing.length} 个待补项`}/>{selected.map(id=><div className="inspect-row" key={id}><TaskIcon type={id}/><div><strong>{TASK_META[id].title}</strong><small>{missing.length?'将生成草稿并标记待补充':'输入信息可进入分析'}</small></div><Badge value={missing.length?'待补充':'可创建'}/></div>)}{missing.length>0&&<div className="missing-box"><AlertTriangle/><div><strong>建议补充</strong><p>{missing.join('、')}</p></div></div>}<p className="tip">组合任务会保存为一个父任务，子任务仍分别进入对应列表，便于独立审核和重试。</p></aside></div>
  </div>;
}

function CasesPage(props:any){
  const {bootstrap,setDrawer,notify}=props;const [tab,setTab]=useState('library');const [q,setQ]=useState('');const [moduleId,setModuleId]=useState('');const [priority,setPriority]=useState('');const [page,setPage]=useState(1);const [pageSize,setPageSize]=useState(20);const [data,setData]=useState<Row>({items:[],total:0,pages:1});const [selected,setSelected]=useState<string[]>([]);const [treeOpen,setTreeOpen]=useState<Record<string,boolean>>({});
  const load=()=>API.list('cases',{q,module_id:moduleId,priority,page,pageSize}).then(setData);useEffect(()=>{load()},[q,moduleId,priority,page,pageSize]);
  const grouped=groupModules(bootstrap.modules,data.items);
  function exportCases(format:'csv'|'xlsx'|'json'){const rows=data.items.filter((x:Row)=>!selected.length||selected.includes(x.id)).map((c:Row)=>({编号:c.code,标题:c.title,模块:c.moduleLabel,优先级:c.priority,类型:c.caseType,状态:c.status,版本:c.version,步骤:(c.content.steps||[]).join('；'),预期:c.content.expected}));downloadRows(rows,`测试用例-${Date.now()}`,format);notify(`已导出 ${rows.length} 条用例`)}
  return <div className="page stack"><PageIntro title="测试用例资产库" desc="按项目、模块、子模块组织，可编辑、执行、关联 Bug、生成回归与报告。" actions={<><button className="button" onClick={()=>exportCases('xlsx')}><Download/>导出 XLSX</button><button className="button primary" onClick={()=>setTab('new')}><Plus/>新增用例</button></>}/><Tabs items={[['library','用例库'],['new','新增 / 智能生成'],['execution','执行记录']]} value={tab} onChange={setTab}/>
    {tab==='library'&&<><div className="filterbar"><SearchBox value={q} onChange={(v:string)=>{setQ(v);setPage(1)}} placeholder="搜索编号、标题或关键词"/><ModuleSelect modules={bootstrap.modules} value={moduleId} onChange={(v:string)=>{setModuleId(v);setPage(1)}} empty="全部模块"/><select value={priority} onChange={e=>setPriority(e.target.value)}><option value="">全部优先级</option><option>P0</option><option>P1</option><option>P2</option></select><button className="button" onClick={()=>{const closed:Record<string,boolean>={};Object.entries(grouped).forEach(([project,mods])=>{closed[project]=false;Object.keys(mods as Row).forEach(mod=>closed[`${project}/${mod}`]=false)});setTreeOpen(closed)}}><Layers3/>全部收起</button></div>
      {selected.length>0&&<div className="bulkbar"><strong>已选 {selected.length} 条</strong><button onClick={()=>notify('已创建用例执行任务')}>创建执行</button><button onClick={()=>notify('已带入 Bug 联合分析')}>联合分析</button><button onClick={()=>props.setPage('regression')}>生成回归</button><button onClick={()=>props.setPage('reports')}>生成报告</button><button onClick={()=>exportCases('csv')}>下载 CSV</button></div>}
      <div className="case-layout"><aside className="panel module-tree"><PanelTitle title="模块树" hint="显示当前筛选数据"/>{Object.entries(grouped).map(([project,mods])=><TreeNode key={project} label={project} count={countTree(mods)} open={treeOpen[project]!==false} toggle={()=>setTreeOpen(s=>({...s,[project]:s[project]===false}))}>{Object.entries(mods as Row).map(([mod,subs])=><TreeNode key={mod} label={mod} count={countTree(subs)} open={treeOpen[`${project}/${mod}`]!==false} toggle={()=>setTreeOpen(s=>({...s,[`${project}/${mod}`]:s[`${project}/${mod}`]===false}))}>{Object.entries(subs as Row).map(([sub,items])=><button className="tree-leaf" key={sub} onClick={()=>setModuleId((items as Row[])[0]?.moduleId)}><span>{sub}</span><b>{(items as Row[]).length}</b></button>)}</TreeNode>)}</TreeNode>)}</aside>
        <section className="panel table-panel"><div className="table-summary"><span>共 <strong>{data.total}</strong> 条 · P0 <strong className="danger-text">{data.items.filter((x:Row)=>x.priority==='P0').length}</strong></span><div><button className="icon-button" onClick={()=>exportCases('json')} title="备份 JSON"><Archive/></button></div></div><div className="table-wrap"><table><thead><tr><th><input type="checkbox" checked={data.items.length>0&&selected.length===data.items.length} onChange={e=>setSelected(e.target.checked?data.items.map((x:Row)=>x.id):[])}/></th><th>用例</th><th>模块</th><th>优先级</th><th>类型</th><th>步骤</th><th>状态</th><th>生成日期</th><th>版本</th></tr></thead><tbody>{data.items.map((c:Row)=><tr key={c.id} onClick={()=>setDrawer({type:'case',item:c})}><td onClick={e=>e.stopPropagation()}><input type="checkbox" checked={selected.includes(c.id)} onChange={()=>setSelected(v=>v.includes(c.id)?v.filter(x=>x!==c.id):[...v,c.id])}/></td><td><strong>{c.title}</strong><small className="id">{c.code}</small></td><td>{shortModule(c.moduleLabel)}</td><td><Badge value={c.priority}/></td><td>{c.caseType}</td><td>{c.content.steps?.length||0}</td><td><Badge value={c.status}/></td><td>{date(c.createdAt)}</td><td>v{c.version}</td></tr>)}</tbody></table></div><Pagination {...data} pageSize={pageSize} setPage={setPage} setPageSize={setPageSize}/></section></div></>}
    {tab==='new'&&<CaseEditor modules={bootstrap.modules} notify={notify} done={()=>{setTab('library');load();props.refresh()}}/>}
    {tab==='execution'&&<Empty title="暂无独立执行批次" desc="勾选用例后点击“创建执行”，执行结果会在这里按批次归档。"/>}
  </div>;
}

function CaseEditor({modules,notify,done}:any){const [form,setForm]=useState({title:'',moduleId:modules[0]?.id||'',priority:'P1',caseType:'功能',precondition:'',steps:'',expected:'',testData:''});const set=(k:string,v:string)=>setForm(s=>({...s,[k]:v}));async function save(){if(!form.title||!form.steps||!form.expected){notify('请补齐标题、步骤和预期结果');return}await API.post('cases',{...form,content:{precondition:form.precondition,steps:form.steps.split('\n').filter(Boolean),expected:form.expected,testData:form.testData}});notify('用例已保存到用例库');done()};return <section className="panel editor"><PanelTitle title="新增测试用例" hint="保存后自动进入当前模块"/><div className="form-grid"><Field label="用例标题" required><input value={form.title} onChange={e=>set('title',e.target.value)} placeholder="清晰描述验证目标"/></Field><Field label="模块" required><ModuleSelect modules={modules} value={form.moduleId} onChange={(v:string)=>set('moduleId',v)}/></Field><Field label="优先级"><select value={form.priority} onChange={e=>set('priority',e.target.value)}><option>P0</option><option>P1</option><option>P2</option></select></Field><Field label="用例类型"><select value={form.caseType} onChange={e=>set('caseType',e.target.value)}><option>功能</option><option>接口</option><option>异常</option><option>回归</option></select></Field><Field label="前置条件" full><textarea value={form.precondition} onChange={e=>set('precondition',e.target.value)}/></Field><Field label="测试步骤（每行一步）" required full><textarea value={form.steps} onChange={e=>set('steps',e.target.value)} placeholder={'1. 准备数据\n2. 执行操作\n3. 检查结果'}/></Field><Field label="预期结果" required full><textarea value={form.expected} onChange={e=>set('expected',e.target.value)}/></Field><Field label="测试数据" full><textarea value={form.testData} onChange={e=>set('testData',e.target.value)}/></Field></div><button className="button primary" onClick={save}><Check/>保存用例</button></section>}

function AnalysisPage({taskType,bootstrap,setDrawer,notify,refresh}:any){const [tab,setTab]=useState('new');const [q,setQ]=useState('');const [data,setData]=useState<Row>({items:[],total:0,pages:1});const [moduleId,setModuleId]=useState(bootstrap.modules[0]?.id||'');const [title,setTitle]=useState('');const [text,setText]=useState('');const [risk,setRisk]=useState('P1');const [running,setRunning]=useState(false);const meta=TASK_META[taskType];const load=()=>API.list('tasks',{type:taskType,q,pageSize:20}).then(setData);useEffect(()=>{load()},[taskType,q]);
  async function run(){if(!title||text.length<10){notify('请填写标题和足够的分析信息');return}setRunning(true);try{let result=localAnalysis(taskType,text),model='本地规则';const provider=bootstrap.providers.find((p:Row)=>p.enabled&&p.keyConfigured);if(provider){try{const ai=await API.post('ai/analyze',{providerId:provider.id,taskType,text});result={...result,...ai.result};model=`${ai.provider} / ${ai.model}`}catch(e:any){notify(`模型暂不可用，已使用本地规则：${e.message}`)}}const item=await API.post('tasks',{type:taskType,title,moduleId,risk:result.risk||risk,status:'待审核',input:{text},result,model});notify('分析任务已生成，请进行人工复核');setDrawer({type:'task',item});setText('');setTitle('');load();refresh()}catch(e:any){notify(e.message)}finally{setRunning(false)}}
  return <div className="page stack"><PageIntro title={meta.title} desc={meta.desc} actions={<button className="button primary" onClick={()=>setTab('new')}><Plus/>新建分析</button>}/><Tabs items={[['new','新建分析'],['list','任务列表'],['knowledge','已入库经验']]} value={tab} onChange={setTab}/>{tab==='new'&&<div className="two-col"><section className="panel smart-panel"><PanelTitle title={`${meta.title} · 智能输入`} hint="支持粘贴文本，也可逐项补充"/><Field label="任务标题" required><input value={title} onChange={e=>setTitle(e.target.value)} placeholder={`例如：${taskType==='bug'?'支付成功订单未同步':taskType==='logs'?'支付回调消费超时':'订单与流水一致性检查'}`}/></Field><div className="inline-grid"><Field label="模块"><ModuleSelect modules={bootstrap.modules} value={moduleId} onChange={setModuleId}/></Field><Field label="风险"><select value={risk} onChange={e=>setRisk(e.target.value)}><option>P0</option><option>P1</option><option>P2</option></select></Field></div><Field label="问题上下文" required><textarea className="large" value={text} onChange={e=>setText(e.target.value)} placeholder={meta.hint}/></Field><div className="smart-actions"><button className="button primary" onClick={run} disabled={running}>{running?<Loader2 className="spin"/>:<Sparkles/>}开始分析</button><label className="button file-button">添加附件<input type="file" onChange={e=>notify(e.target.files?.[0]?`已选择 ${e.target.files[0].name}`:'')}/></label></div></section><aside className="panel"><PanelTitle title="输入完整度" hint="不会编造缺失内容"/><Completeness text={text} required={meta.required}/><div className="result-preview"><h4>输出结构</h4>{outputSections(taskType).map(x=><div key={x}><Check/><span>{x}</span></div>)}</div></aside></div>}
    {tab==='list'&&<section className="panel table-panel"><div className="filterbar"><SearchBox value={q} onChange={setQ} placeholder="搜索任务标题、状态"/><span className="summary">共 {data.total} 个任务</span></div><TaskTable items={data.items} open={(i:Row)=>setDrawer({type:'task',item:i})}/></section>}
    {tab==='knowledge'&&<KnowledgeExperience category={taskType==='bug'?'历史 Bug 库':taskType==='logs'?'日志规律库':'SQL 经验库'} open={(i:Row)=>setDrawer({type:'knowledge',item:i})}/>}</div>;
}

function RegressionPage({setDrawer,notify,refresh}:any){const [tab,setTab]=useState('lists');const [data,setData]=useState<Row>({items:[]});const load=()=>API.list('regressions').then(setData);useEffect(()=>{load()},[]);return <div className="page stack"><PageIntro title="回归测试清单" desc="从高风险用例、历史 Bug 和变更模块生成可执行清单。" actions={<><button className="button" onClick={()=>exportRegression(data.items[0],notify)}><Download/>下载 XLSX</button><button className="button primary" onClick={()=>setTab('generate')}><Plus/>生成清单</button></>}/><Tabs items={[['lists','回归清单'],['generate','生成回归'],['history','完成记录']]} value={tab} onChange={setTab}/>{tab==='lists'&&<div className="stack">{data.items.map((r:Row)=><section className="panel regression-card" key={r.id}><div className="reg-head"><div><div className="title-line"><h3>{r.title}</h3><Badge value={r.status}/></div><p>{r.data.version} · {date(r.updatedAt)} · {r.data.items.length} 项</p></div><div className="progress-ring" style={{'--progress':`${r.progress*3.6}deg`} as React.CSSProperties}><strong>{r.progress}%</strong></div></div><div className="progress"><i style={{width:`${r.progress}%`}}/></div><div className="reg-items">{r.data.items.map((item:Row)=><div className="reg-item" key={item.id}><Badge value={item.priority}/><div><strong>{item.title}</strong><small>{shortModule(item.moduleId?moduleFromId(item.moduleId):'')} · {item.caseId?'关联用例':'关联 Bug'}</small></div><select value={item.status} onChange={async e=>{item.status=e.target.value;await API.patch('regressions',r.id,{data:r.data});notify('执行状态已更新');load();refresh()}}><option>未执行</option><option>通过</option><option>失败</option><option>阻塞</option><option>跳过</option></select><button className="text-button" onClick={()=>setDrawer({type:'regression-item',item})}>查看</button></div>)}</div><div className="reg-footer"><span><b className="success-text">{r.data.items.filter((x:Row)=>x.status==='通过').length}</b> 通过 · <b className="danger-text">{r.data.items.filter((x:Row)=>x.status==='失败').length}</b> 失败 · {r.data.items.filter((x:Row)=>x.status==='阻塞').length} 阻塞</span><button className="button" onClick={()=>navigator.clipboard.writeText(regressionText(r)).then(()=>notify('回归清单已复制'))}><Copy/>复制清单</button></div></section>)}</div>}{tab==='generate'&&<GenerateRegression notify={notify} done={()=>{setTab('lists');load()}}/>}{tab==='history'&&<Empty title="暂无已完成回归" desc="所有必选项完成后，清单会自动归档到这里。"/>}</div>}

function GenerateRegression({notify,done}:any){const [title,setTitle]=useState('');const [change,setChange]=useState('');return <section className="panel smart-panel"><PanelTitle title="生成回归清单" hint="系统将优先纳入 P0/P1、失败用例与历史缺陷"/><Field label="版本 / 清单标题" required><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="例如：v2.9.0 支付中心回归"/></Field><Field label="变更内容与影响模块" required><textarea className="large" value={change} onChange={e=>setChange(e.target.value)}/></Field><button className="button primary" onClick={()=>{notify('已按风险规则生成回归草稿');done()}}><Sparkles/>分析并生成</button></section>}

function ReportsPage({setDrawer,notify,refresh}:any){const [tab,setTab]=useState('list');const [data,setData]=useState<Row>({items:[]});const [tasks,setTasks]=useState<Row[]>([]);const [selected,setSelected]=useState<string[]>([]);const [title,setTitle]=useState('');const [version,setVersion]=useState('');const [verdict,setVerdict]=useState('有条件上线');const load=()=>API.list('reports').then(setData);useEffect(()=>{load();API.list('tasks',{pageSize:100}).then(r=>setTasks(r.items))},[]);
  async function generate(){if(!title||!version){notify('请填写报告标题和版本');return}const chosen=tasks.filter(t=>selected.includes(t.id));const report=await API.post('reports',{title,projectName:'电商平台',version,verdict,data:{modules:[...new Set(chosen.map(x=>shortModule(x.moduleLabel)))],passed:chosen.filter(x=>x.status==='已完成').length,failed:chosen.filter(x=>x.risk==='P0').length,blocked:chosen.filter(x=>x.status==='阻塞').length,sources:chosen.map(x=>({type:'task',id:x.id})),risks:chosen.filter(x=>x.risk==='P0').map(x=>x.title)}});notify('测试报告已生成');setDrawer({type:'report',item:report});setTab('list');load();refresh()}
  return <div className="page stack"><PageIntro title="测试报告" desc="勾选用例、Bug、分析任务和回归结果，输出统一质量结论。" actions={<button className="button primary" onClick={()=>setTab('new')}><Plus/>生成报告</button>}/><Tabs items={[['list','报告列表'],['new','生成报告'],['template','报告模板']]} value={tab} onChange={setTab}/>{tab==='list'&&<section className="panel table-panel"><div className="table-wrap"><table><thead><tr><th>报告</th><th>项目 / 版本</th><th>覆盖模块</th><th>结论</th><th>失败</th><th>阻塞</th><th>报告日期</th></tr></thead><tbody>{data.items.map((r:Row)=><tr key={r.id} onClick={()=>setDrawer({type:'report',item:r})}><td><strong>{r.title}</strong><small className="id">{r.id}</small></td><td>{r.projectName}<small>{r.version}</small></td><td>{(r.data.modules||[]).join('、')}</td><td><Badge value={r.verdict}/></td><td>{r.data.failed||0}</td><td>{r.data.blocked||0}</td><td>{date(r.createdAt)}</td></tr>)}</tbody></table></div></section>}{tab==='new'&&<div className="two-col"><section className="panel editor"><PanelTitle title="报告信息" hint="统一模板 v1.0"/><Field label="报告标题" required><input value={title} onChange={e=>setTitle(e.target.value)}/></Field><div className="inline-grid"><Field label="发布版本" required><input value={version} onChange={e=>setVersion(e.target.value)} placeholder="v2.9.0"/></Field><Field label="上线结论"><select value={verdict} onChange={e=>setVerdict(e.target.value)}><option>可上线</option><option>有条件上线</option><option>不能上线</option></select></Field></div><button className="button primary" onClick={generate}><FileBarChart/>生成统一报告</button></section><section className="panel source-picker"><PanelTitle title="选择报告来源" hint={`已选 ${selected.length} 项`}/>{tasks.map(t=><label key={t.id}><input type="checkbox" checked={selected.includes(t.id)} onChange={()=>setSelected(v=>v.includes(t.id)?v.filter(x=>x!==t.id):[...v,t.id])}/><TaskIcon type={t.type}/><span><strong>{t.title}</strong><small>{TASK_META[t.type]?.title} · {shortModule(t.moduleLabel)}</small></span><Badge value={t.risk}/></label>)}</section></div>}{tab==='template'&&<TemplateNotice name="测试报告"/>}</div>}

function KnowledgePage({bootstrap,setDrawer,notify,refresh}:any){const [q,setQ]=useState('');const [category,setCategory]=useState('');const [status,setStatus]=useState('');const [moduleId,setModuleId]=useState('');const [page,setPage]=useState(1);const [pageSize,setPageSize]=useState(20);const [data,setData]=useState<Row>({items:[],pages:1,total:0});const [newOpen,setNewOpen]=useState(false);const load=()=>API.list('knowledge',{q,category,status,module_id:moduleId,page,pageSize}).then(setData);useEffect(()=>{load()},[q,category,status,moduleId,page,pageSize]);return <div className="page stack"><PageIntro title="知识库中心" desc="点击任意记录查看正文、版本、来源、审核和引用关系。" actions={<><button className="button"><Download/>批量导入</button><button className="button primary" onClick={()=>setNewOpen(true)}><Plus/>新增知识</button></>}/><div className="metric-grid four"><Metric label="有效知识" value={data.items.filter((x:Row)=>x.status==='已发布').length}/><Metric label="待审核" value={data.items.filter((x:Row)=>x.status==='待审核').length}/><Metric label="分类覆盖" value={`${new Set(data.items.map((x:Row)=>x.category)).size}/7`}/><Metric label="知识总量" value={data.total}/></div><div className="filterbar"><SearchBox value={q} onChange={setQ} placeholder="搜索标题、正文和分类"/><select value={category} onChange={e=>setCategory(e.target.value)}><option value="">全部分类</option>{KB_CATEGORIES.map(x=><option key={x}>{x}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">全部状态</option><option>待审核</option><option>已发布</option><option>已驳回</option><option>已撤销</option></select><ModuleSelect modules={bootstrap.modules} value={moduleId} onChange={setModuleId} empty="全部模块"/></div><section className="panel table-panel"><div className="table-wrap"><table><thead><tr><th>知识标题</th><th>分类</th><th>模块</th><th>风险</th><th>版本</th><th>状态</th><th>更新时间</th><th/></tr></thead><tbody>{data.items.map((k:Row)=><tr key={k.id} onClick={()=>setDrawer({type:'knowledge',item:k})}><td><strong className="link-title">{k.title}</strong><small className="id">{k.id}</small></td><td>{k.category}</td><td>{shortModule(k.moduleLabel)}</td><td><Badge value={k.risk}/></td><td>v{k.version}</td><td><Badge value={k.status}/></td><td>{date(k.updatedAt)}</td><td><button className="text-button">查看 <ChevronRight/></button></td></tr>)}</tbody></table></div><Pagination {...data} pageSize={pageSize} setPage={setPage} setPageSize={setPageSize}/></section>{newOpen&&<KnowledgeModal modules={bootstrap.modules} close={()=>setNewOpen(false)} done={()=>{setNewOpen(false);load();refresh()}} notify={notify}/>}</div>}

function WorkflowPage({notify,refresh,setDrawer}:any){const [data,setData]=useState<Row>({items:[]});const [name,setName]=useState('');const [steps,setSteps]=useState(['bug','logs','sql','regression','report']);const load=()=>API.list('workflows').then(setData);useEffect(()=>{load()},[]);async function save(){if(!name){notify('请输入链路名称');return}await API.post('workflows',{name,steps});notify('全链路模板已保存');setName('');load();refresh()};return <div className="page stack"><PageIntro title="全链路与组合任务" desc="父任务汇总进度，子任务保留独立输入、结果、审核和重试记录。"/><div className="two-col"><section className="panel"><PanelTitle title="创建链路模板" hint="点击节点启用或停用"/><Field label="链路名称"><input value={name} onChange={e=>setName(e.target.value)} placeholder="例如：支付异常完整排查链"/></Field><div className="workflow-builder">{Object.keys(TASK_META).map((id,index)=><React.Fragment key={id}><button className={steps.includes(id)?'active':''} onClick={()=>setSteps(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id])}><TaskIcon type={id}/><span>{TASK_META[id].title}</span><small>{steps.includes(id)?'必选步骤':'未启用'}</small></button>{index<5&&<ChevronRight/>}</React.Fragment>)}</div><div className="missing-box"><AlertTriangle/><div><strong>启动前补充</strong><p>环境、版本、影响模块与至少一项问题证据。后续节点会复用上一步结构化结果。</p></div></div><button className="button primary" onClick={save}><Check/>保存链路模板</button></section><aside className="panel"><PanelTitle title="执行规则" hint="父子任务结构"/><ol className="rule-list"><li>创建父任务，记录整体范围和最终产物。</li><li>每个节点生成独立子任务并进入对应列表。</li><li>缺项节点暂停并提示，已完成结果不回滚。</li><li>全部必选节点完成后才允许结束链路。</li></ol></aside></div><section className="panel"><PanelTitle title="已保存链路" hint={`${data.items.length} 个模板`}/><div className="workflow-cards">{data.items.map((w:Row)=><button key={w.id} onClick={()=>setDrawer({type:'workflow',item:w})}><div><GitBranch/><strong>{w.name}</strong></div><div className="mini-flow">{w.steps.map((s:string)=><span key={s}>{TASK_META[s]?.title}</span>)}</div><footer><Badge value={w.status}/><span>更新于 {date(w.updatedAt)}</span><Play/></footer></button>)}</div></section></div>}

function SettingsPage({bootstrap,refresh,notify}:any){const [tab,setTab]=useState('modules');return <div className="page stack"><PageIntro title="配置中心" desc="配置三级模块、模型厂商、输出模板和任务关联规则。"/><Tabs items={[['modules','项目与模块'],['models','大模型'],['templates','格式模板'],['relations','关联规则']]} value={tab} onChange={setTab}/>{tab==='modules'&&<ModuleSettings {...{bootstrap,refresh,notify}}/>}{tab==='models'&&<ModelSettings {...{bootstrap,refresh,notify}}/>}{tab==='templates'&&<TemplateSettings notify={notify}/>} {tab==='relations'&&<RelationSettings/>}</div>}

function ModuleSettings({bootstrap,refresh,notify}:any){const [form,setForm]=useState({projectName:'',moduleName:'',submoduleName:''});async function add(){if(Object.values(form).some(v=>!v)){notify('请填写完整的三级模块');return}await API.post('modules',form);notify('模块已添加');setForm({projectName:'',moduleName:'',submoduleName:''});refresh()};return <div className="two-col wide-left"><section className="panel"><PanelTitle title="三级模块结构" hint="停用后不再出现在新建表单中"/><div className="module-admin">{Object.entries(groupBy(bootstrap.modules,'projectName')).map(([project,mods])=><div className="project-group" key={project}><h3><Layers3/>{project}<Badge value="项目"/></h3>{Object.entries(groupBy(mods as Row[],'moduleName')).map(([mod,subs])=><div key={mod} className="module-group"><strong>{mod}</strong>{(subs as Row[]).map(s=><div className="submodule-row" key={s.id}><span>{s.submoduleName}</span><small>更新 {date(s.updatedAt)}</small><Badge value={s.status}/><button className="text-button" onClick={async()=>{await API.patch('modules',s.id,{status:s.status==='启用'?'停用':'启用'});notify(`已${s.status==='启用'?'停用':'恢复'}模块`);refresh()}}>{s.status==='启用'?'停用':'恢复'}</button></div>)}</div>)}</div>)}</div></section><aside className="panel"><PanelTitle title="新增模块" hint="项目 → 模块 → 子模块"/><Field label="项目"><input value={form.projectName} onChange={e=>setForm({...form,projectName:e.target.value})}/></Field><Field label="模块"><input value={form.moduleName} onChange={e=>setForm({...form,moduleName:e.target.value})}/></Field><Field label="子模块"><input value={form.submoduleName} onChange={e=>setForm({...form,submoduleName:e.target.value})}/></Field><button className="button primary full" onClick={add}><Plus/>添加三级模块</button></aside></div>}

function ModelSettings({bootstrap,refresh,notify}:any){const [selected,setSelected]=useState(bootstrap.providers[0]?.id);const p=bootstrap.providers.find((x:Row)=>x.id===selected)||bootstrap.providers[0];const [form,setForm]=useState<Row>(p||{});useEffect(()=>setForm(p||{}),[selected,p?.updatedAt]);async function save(){await API.patch('providers',p.id,{...form,enabled:Boolean(form.enabled)});notify('模型配置已安全保存');refresh()}async function test(){try{const r=await API.request(`/providers/${p.id}/test`,{method:'POST'});notify(`连接成功，耗时 ${r.latency}ms`)}catch(e:any){notify(e.message)}}return <div className="settings-layout"><aside className="panel provider-list">{bootstrap.providers.map((x:Row)=><button className={selected===x.id?'active':''} onClick={()=>setSelected(x.id)} key={x.id}><Bot/><span><strong>{x.name}</strong><small>{x.model||'待配置'}</small></span><i className={x.enabled?'on':''}/></button>)}</aside><section className="panel editor"><PanelTitle title={`${p.name} 配置`} hint="API Key 存入 macOS 钥匙串，不写入数据库"/><div className="form-grid"><Field label="Base URL" full><input value={form.baseUrl||''} onChange={e=>setForm({...form,baseUrl:e.target.value})}/></Field><Field label="模型名"><input value={form.model||''} onChange={e=>setForm({...form,model:e.target.value})}/></Field><Field label="API Key"><input type="password" value={form.apiKey||''} onChange={e=>setForm({...form,apiKey:e.target.value})} placeholder={p.keyConfigured?p.keyMask:'输入后安全保存'}/></Field><Field label="温度"><input type="number" step="0.1" min="0" max="2" value={form.temperature||0.2} onChange={e=>setForm({...form,temperature:Number(e.target.value)})}/></Field><Field label="超时（秒）"><input type="number" value={form.timeout||60} onChange={e=>setForm({...form,timeout:Number(e.target.value)})}/></Field><Field label="最大输出"><input type="number" value={form.maxTokens||4096} onChange={e=>setForm({...form,maxTokens:Number(e.target.value)})}/></Field><Field label="启用厂商"><label className="switch"><input type="checkbox" checked={Boolean(form.enabled)} onChange={e=>setForm({...form,enabled:e.target.checked})}/><i/><span>{form.enabled?'已启用':'未启用'}</span></label></Field></div><div className="smart-actions"><button className="button primary" onClick={save}><Check/>保存配置</button><button className="button" onClick={test}><RefreshCw/>测试连接</button></div></section></div>}

function TemplateSettings({notify}:any){const [task,setTask]=useState('cases');const defaults=['标题','模块','前置条件','测试步骤','预期结果','优先级'];const [fields,setFields]=useState(defaults);useEffect(()=>{API.get('settings',`template-${task}`).then(r=>setFields(r.value?.fields||defaults)).catch(()=>setFields(defaults))},[task]);async function save(){await API.patch('settings',`template-${task}`,{value:{fields,updatedAt:new Date().toISOString(),syncMode:'all-history'}});notify('模板已保存，历史记录已按新格式同步')}return <div className="two-col"><aside className="panel"><PanelTitle title="模板类型"/>{Object.entries(TASK_META).map(([id,m])=><button className={`template-item ${task===id?'active':''}`} onClick={()=>setTask(id)} key={id}><TaskIcon type={id}/><span>{m.title}</span><ChevronRight/></button>)}</aside><section className="panel"><PanelTitle title={`${TASK_META[task].title}格式`} hint="保存会全量同步历史展示"/><div className="field-list">{fields.map((f,i)=><div key={`${f}-${i}`}><Menu/><input value={f} onChange={e=>setFields(v=>v.map((x,n)=>n===i?e.target.value:x))}/><Badge value={i<3?'必填':'可选'}/><button className="icon-button" onClick={()=>setFields(v=>v.filter((_,n)=>n!==i))}><X/></button></div>)}</div><button className="button" onClick={()=>setFields(v=>[...v,'新字段'])}><Plus/>添加字段</button><div className="warning"><AlertTriangle/><p><strong>全量同步提醒</strong><br/>新增字段会在历史记录中显示“待补齐”；删除字段从当前页面隐藏，但原始快照仍保留。</p></div><button className="button primary" onClick={save}><Check/>确认并全量同步</button></section></div>}

function RelationSettings(){return <section className="panel"><PanelTitle title="任务与知识关联" hint="发布知识后自动进入对应任务的检索范围"/><div className="relation-grid">{Object.entries(TASK_META).map(([id,m])=><div key={id}><TaskIcon type={id}/><strong>{m.title}</strong><div>{(id==='bug'?['历史 Bug 库','日志规律库','业务规则库']:id==='logs'?['日志规律库','接口异常库','历史 Bug 库']:id==='sql'?['SQL 经验库','业务规则库']:['业务规则库','回归规则库','历史 Bug 库']).map(x=><Badge key={x} value={x}/>)}</div></div>)}</div></section>}

function DetailDrawer({drawer,close,notify,refresh,setPage}:any){const [item,setItem]=useState(drawer.item);const [editing,setEditing]=useState(false);const [audit,setAudit]=useState<Row[]>([]);useEffect(()=>{const resource=drawer.type==='case'?'cases':drawer.type==='knowledge'?'knowledge':drawer.type==='task'?'tasks':'';const type=resource?resource.replace(/s$/,''):'';if(resource){API.get(resource,item.id).then(setItem);API.request(`/audit?type=${type}&id=${item.id}`).then(r=>setAudit(r.items))}},[item.id,drawer.type]);async function knowledgeAction(action:string){try{const next=await API.patch('knowledge',item.id,{action});setItem(next);notify(action==='approve'?'知识已审核发布':action==='withdraw'?'知识已撤销入库':'操作完成');refresh()}catch(e:any){notify(e.data?.dependencies?`${e.message}：${e.data.dependencies.map((x:Row)=>`${x.source_type}(${x.source_id})`).join('、')}`:e.message)}}async function taskAction(action:string){const payload=action==='submit'?{reviewStatus:'待审核',status:'待审核',action:'提交审核'}:action==='approve'?{reviewStatus:'审核通过',status:'已完成',action:'审核通过'}:{reviewStatus:'已驳回',status:'待补充',action:'审核驳回'};const next=await API.patch('tasks',item.id,payload);setItem(next);notify('任务状态已更新');refresh()}
  return <div className="overlay" onMouseDown={e=>e.target===e.currentTarget&&close()}><aside className="drawer"><header><div><span className="eyebrow">DETAIL VIEW</span><h2>{item.title||item.name}</h2><small>{item.id}</small></div><button className="icon-button" onClick={close}><X/></button></header><div className="drawer-body">
    {drawer.type==='knowledge'&&<><div className="detail-badges"><Badge value={item.category}/><Badge value={item.risk}/><Badge value={item.status}/><span>v{item.version}</span></div><DetailGrid rows={[['所属模块',item.moduleLabel||'未关联'],['来源任务',item.sourceTaskId||'人工维护'],['更新时间',dateTime(item.updatedAt)],['引用次数',`${item.referenceCount??0}${item.referenceCount?'（撤销将被阻止）':'（当前无下游阻塞）'}`]]}/>{item.dependencies?.length>0&&<section className="detail-section"><h3>关联影响</h3>{item.dependencies.map((d:Row)=><p key={d.id}>{d.label}：{d.sourceType} / {d.sourceId}</p>)}</section>}<section className="detail-section"><h3>知识正文</h3>{editing?<textarea value={item.content} onChange={e=>setItem({...item,content:e.target.value})}/>:<p className="content-text">{item.content}</p>}</section><section className="detail-section"><h3>审核信息</h3><p>{item.reviewNote||'暂无审核备注'}</p></section><div className="drawer-actions">{editing?<button className="button primary" onClick={async()=>{const n=await API.patch('knowledge',item.id,{content:item.content,title:item.title});setItem(n);setEditing(false);notify('已创建知识新版本')}}><Check/>保存新版本</button>:<button className="button" onClick={()=>setEditing(true)}>编辑内容</button>}{item.status==='待审核'&&<button className="button primary" onClick={()=>knowledgeAction('approve')}>审核通过并发布</button>}{item.status==='已发布'&&<button className="button danger" onClick={()=>knowledgeAction('withdraw')}><RotateCcw/>撤销入库</button>}</div></>}
    {drawer.type==='case'&&<><div className="detail-badges"><Badge value={item.priority}/><Badge value={item.caseType}/><Badge value={item.status}/><span>v{item.version}</span></div><DetailGrid rows={[['用例编号',item.code],['所属模块',item.moduleLabel],['生成日期',date(item.createdAt)],['关联 Bug','0']]}/><section className="detail-section"><h3>前置条件</h3><p>{item.content.precondition||'无'}</p></section><section className="detail-section"><h3>测试步骤</h3><ol>{(item.content.steps||[]).map((s:string,i:number)=><li key={i}>{s}</li>)}</ol></section><section className="detail-section result-box"><h3>预期结果</h3><p>{item.content.expected}</p></section><section className="detail-section"><h3>测试数据</h3><p>{item.content.testData||'未填写'}</p></section><div className="drawer-actions"><button className="button" onClick={()=>notify('已复制为一条新用例')}><Copy/>复制用例</button><button className="button primary" onClick={()=>setEditing(true)}>编辑并升版</button></div></>}
    {drawer.type==='task'&&<><div className="detail-badges"><Badge value={TASK_META[item.type]?.title||'组合任务'}/><Badge value={item.risk}/><Badge value={item.status}/><Badge value={item.reviewStatus}/></div><DetailGrid rows={[['所属模块',item.moduleLabel||'未指定'],['分析模型',item.model],['创建时间',dateTime(item.createdAt)],['知识状态',item.knowledgeStatus]]}/><section className="detail-section"><h3>输入信息</h3><pre>{pretty(item.input)}</pre></section><section className="detail-section result-box"><h3>分析结果</h3><pre>{pretty(item.result)}</pre></section><div className="drawer-actions">{item.reviewStatus==='未提交'&&<button className="button primary" onClick={()=>taskAction('submit')}>提交审核</button>}{item.reviewStatus==='待审核'&&<><button className="button primary" onClick={()=>taskAction('approve')}>审核通过</button><button className="button danger" onClick={()=>taskAction('reject')}>驳回</button></>} {item.reviewStatus==='审核通过'&&item.knowledgeStatus!=='已入库'&&<button className="button primary" onClick={async()=>{const cat=item.type==='bug'?'历史 Bug 库':item.type==='logs'?'日志规律库':'SQL 经验库';await API.post('knowledge',{title:item.title,category:cat,moduleId:item.moduleId,risk:item.risk,content:pretty(item.result),sourceTaskId:item.id});await API.patch('tasks',item.id,{knowledgeStatus:'待审核',action:'发起知识入库'});notify('已生成待审核知识');refresh();setPage('knowledge');close()}}>申请入知识库</button>}</div></>}
    {drawer.type==='report'&&<ReportDetail item={item} notify={notify}/>} {drawer.type==='workflow'&&<WorkflowDetail item={item}/>} {drawer.type==='regression-item'&&<RegressionItemDetail item={item}/>} 
    {audit.length>0&&<section className="detail-section"><h3>操作记录</h3><div className="timeline">{audit.map(a=><div key={a.id}><i/><span><strong>{a.action}</strong><small>{dateTime(a.createdAt)} {a.detail}</small></span></div>)}</div></section>}
  </div></aside></div>}

function ReportDetail({item,notify}:any){const markdown=reportMarkdown(item);return <><div className="report-verdict"><span>上线结论</span><Badge value={item.verdict}/><strong>{item.version}</strong></div><DetailGrid rows={[['报告日期',date(item.createdAt)],['项目',item.projectName],['覆盖模块',(item.data.modules||[]).join('、')||'未指定'],['数据来源',`${item.data.sources?.length||0} 项`]]}/><section className="detail-section"><h3>执行结果</h3><div className="report-numbers"><span><b>{item.data.passed||0}</b>通过</span><span><b>{item.data.failed||0}</b>失败</span><span><b>{item.data.blocked||0}</b>阻塞</span></div></section><section className="detail-section"><h3>风险与遗留问题</h3><ul>{(item.data.risks||['无']).map((x:string)=><li key={x}>{x}</li>)}</ul></section><div className="drawer-actions"><button className="button" onClick={()=>navigator.clipboard.writeText(markdown).then(()=>notify('报告已复制'))}><Copy/>复制</button><button className="button" onClick={()=>downloadText(markdown,`${item.title}.md`)}><Download/>Markdown</button><button className="button primary" onClick={()=>downloadPdf(item)}><Download/>PDF</button></div></>}
function WorkflowDetail({item}:any){return <><div className="detail-badges"><Badge value={item.status}/><span>{item.steps.length} 个必选节点</span></div><div className="vertical-flow">{item.steps.map((s:string,i:number)=><div key={s}><span>{i+1}</span><TaskIcon type={s}/><div><strong>{TASK_META[s]?.title}</strong><small>{i===0?'等待启动':'接收上一步结构化结果'}</small></div><Badge value={i===0?'可开始':'等待'}/></div>)}</div><button className="button primary full"><Play/>启动全链路任务</button></>}
function RegressionItemDetail({item}:any){return <><div className="detail-badges"><Badge value={item.priority}/><Badge value={item.status}/></div><DetailGrid rows={[['负责人',item.owner],['关联记录',item.caseId||item.bugId],['功能模块',moduleFromId(item.moduleId)],['执行状态',item.status]]}/><section className="detail-section"><h3>预期结果</h3><p>{item.expected}</p></section><section className="detail-section"><h3>实际结果</h3><p>{item.actual||'待执行后填写'}</p></section></>}

function KnowledgeModal({modules,close,done,notify}:any){const [form,setForm]=useState({title:'',category:'业务规则库',moduleId:modules[0]?.id||'',risk:'P1',content:''});async function save(){if(!form.title||!form.content){notify('请填写标题和正文');return}await API.post('knowledge',form);notify('知识已保存为待审核');done()}return <div className="overlay modal-layer"><div className="modal"><header><h2>新增知识</h2><button className="icon-button" onClick={close}><X/></button></header><Field label="知识标题" required><input value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></Field><div className="inline-grid"><Field label="知识分类"><select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{KB_CATEGORIES.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="风险"><select value={form.risk} onChange={e=>setForm({...form,risk:e.target.value})}><option>P0</option><option>P1</option><option>P2</option></select></Field></div><Field label="所属模块"><ModuleSelect modules={modules} value={form.moduleId} onChange={(v:string)=>setForm({...form,moduleId:v})}/></Field><Field label="知识正文" required><textarea className="large" value={form.content} onChange={e=>setForm({...form,content:e.target.value})}/></Field><footer><button className="button" onClick={close}>取消</button><button className="button primary" onClick={save}>保存并提交审核</button></footer></div></div>}
function MigrationModal({data,close,done,notify}:any){const taskCount=data.tasks?.length||0,kbCount=data.knowledge?.length||0;async function migrate(){try{const r=await API.post('migrate',data);notify(r.migrated?`已迁移 ${r.imported.tasks+ r.imported.knowledge} 条旧数据`:'旧数据已经迁移过');done()}catch(e:any){notify(`迁移失败：${e.message}`)}}return <div className="overlay modal-layer"><div className="modal small-modal"><div className="migration-icon"><Database/></div><h2>发现旧版工作台数据</h2><p>检测到 {taskCount} 个任务和 {kbCount} 条知识。导入前会在本机生成只读 JSON 备份，重复操作不会产生重复数据。</p><footer><button className="button" onClick={close}>暂不迁移</button><button className="button primary" onClick={migrate}>备份并迁移到 SQLite</button></footer></div></div>}

function TaskTable({items,open}:any){return <div className="table-wrap"><table><thead><tr><th>任务</th><th>模块</th><th>风险</th><th>状态</th><th>模型</th><th>审核</th><th>知识</th><th>创建时间</th></tr></thead><tbody>{items.map((t:Row)=><tr key={t.id} onClick={()=>open(t)}><td><strong>{t.title}</strong><small className="id">{t.id}</small></td><td>{shortModule(t.moduleLabel)}</td><td><Badge value={t.risk}/></td><td><Badge value={t.status}/></td><td>{t.model}</td><td><Badge value={t.reviewStatus}/></td><td><Badge value={t.knowledgeStatus}/></td><td>{date(t.createdAt)}</td></tr>)}</tbody></table>{!items.length&&<Empty title="没有匹配任务" desc="新建分析后，记录会保存在这里。"/>}</div>}
function KnowledgeExperience({category,open}:any){const [items,setItems]=useState<Row[]>([]);useEffect(()=>{API.list('knowledge',{category,status:'已发布'}).then(r=>setItems(r.items))},[category]);return <section className="panel"><PanelTitle title={category} hint="审核发布后可被分析任务引用"/><div className="knowledge-cards">{items.map(k=><button key={k.id} onClick={()=>open(k)}><div><Badge value={k.risk}/><Badge value={k.status}/></div><h3>{k.title}</h3><p>{k.content}</p><footer>{shortModule(k.moduleLabel)}<ChevronRight/></footer></button>)}</div></section>}

function PanelTitle({title,hint,action}:any){return <div className="panel-title"><div><h3>{title}</h3>{hint&&<p>{hint}</p>}</div>{action}</div>}
function PageIntro({title,desc,actions}:any){return <div className="page-intro"><div><h2>{title}</h2><p>{desc}</p></div><div className="page-actions">{actions}</div></div>}
function Tabs({items,value,onChange}:any){return <div className="tabs">{items.map(([id,label]:string[])=><button key={id} className={value===id?'active':''} onClick={()=>onChange(id)}>{label}</button>)}</div>}
function Metric({label,value}:any){return <article className="metric"><span>{label}</span><strong>{value}</strong></article>}
function Asset({label,value,onClick}:any){return <button onClick={onClick}><span>{label}</span><strong>{value}</strong><ChevronRight/></button>}
function Field({label,required,full,children}:any){return <label className={`field ${full?'full':''}`}><span>{label}{required&&<em>*</em>}</span>{children}</label>}
function SearchBox({value,onChange,placeholder}:any){return <label className="search"><Search/><input value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/>{value&&<button onClick={()=>onChange('')}><X/></button>}</label>}
function ModuleSelect({modules,value,onChange,empty}:any){return <select value={value} onChange={e=>onChange(e.target.value)}>{empty&&<option value="">{empty}</option>}{modules.filter((m:Row)=>m.status==='启用'||m.id===value).map((m:Row)=><option key={m.id} value={m.id}>{m.projectName} / {m.moduleName} / {m.submoduleName}</option>)}</select>}
function Badge({value}:any){return <span className={`badge ${badgeClass(String(value))}`}>{value||'—'}</span>}
function TaskIcon({type}:any){const C=type==='bug'?Bug:type==='logs'?SquareTerminal:type==='sql'?Database:type==='regression'?ClipboardCheck:type==='report'?FileBarChart:type==='cases'?ListChecks:GitBranch;return <span className="task-icon"><C/></span>}
function Empty({title,desc}:any){return <div className="empty"><FileText/><strong>{title}</strong><p>{desc}</p></div>}
function DetailGrid({rows}:any){return <div className="detail-grid">{rows.map(([a,b]:string[])=><div key={a}><span>{a}</span><strong>{b||'—'}</strong></div>)}</div>}
function Pagination({page,pages,total,pageSize,setPage,setPageSize}:any){return <div className="pagination"><span>共 {total} 条</span><select value={pageSize} onChange={e=>{setPageSize(Number(e.target.value));setPage(1)}}><option>20</option><option>50</option><option>100</option></select><button disabled={page<=1} onClick={()=>setPage(page-1)}><ChevronLeft/></button><b>{page} / {pages}</b><button disabled={page>=pages} onClick={()=>setPage(page+1)}><ChevronRight/></button></div>}
function TreeNode({label,count,open,toggle,children}:any){return <div className="tree-node"><button onClick={toggle}><ChevronDown className={open?'':'closed'}/><strong>{label}</strong><b>{count}</b></button>{open&&<div>{children}</div>}</div>}
function Completeness({text,required}:any){const score=Math.min(100,Math.round(text.trim().length/1.2));return <><div className="score"><strong>{score}%</strong><span>当前输入完整度</span></div><div className="progress"><i style={{width:`${score}%`}}/></div><div className="check-list">{required.map((x:string,i:number)=><div key={x}><span className={text.length>(i+1)*25?'done':''}>{text.length>(i+1)*25?<Check/>:<AlertTriangle/>}</span><strong>{x}</strong><small>{text.length>(i+1)*25?'已识别':'建议补充'}</small></div>)}</div></>}
function TemplateNotice({name}:any){return <section className="panel"><PanelTitle title={`${name}统一模板`} hint="当前版本 v1.0"/><div className="warning"><AlertTriangle/><p>模板修改统一在“配置中心 → 格式模板”完成。保存后历史记录会同步新结构，新增字段显示“待补齐”，原始快照不受影响。</p></div></section>}

function localAnalysis(type:string,text:string){const high=/生产|资损|重复扣款|数据丢失|安全|全量/.test(text);const common={summary:text.slice(0,120),risk:high?'P0':'P1',missingFields:text.length<40?TASK_META[type].required:[],evidence:['用户输入','项目模块配置'],suggestions:[] as string[]};const map:Row={bug:['核对最近变更与复现路径','按 traceId 串联接口、日志与数据','覆盖受影响模块及历史高风险用例'],logs:['按时间窗口还原调用链','定位首个异常节点并保留上下文','补充同 traceId 的上下游日志'],sql:['检查过滤条件、索引与执行计划','验证事务隔离和状态一致性','在测试环境执行验证 SQL'],cases:['覆盖正常、异常、边界和权限场景','P0 优先覆盖资金与核心链路','生成后需人工确认预期结果']};common.suggestions=map[type]||['结合历史风险生成结构化结论','保留来源并进行人工复核'];return common}
function outputSections(type:string){return type==='logs'?['异常摘要','关键时间线','错误片段','可能原因','排查建议']:type==='sql'?['SQL 正确性','性能风险','影响范围','优化建议','审核结论']:type==='bug'?['影响模块','证据链','可能原因','排查路径','回归范围']:['结构化结果','风险等级','缺失信息','人工复核点']}
function guessTitle(text:string,fallback:string){return text.split(/[。\n]/)[0].slice(0,35)||fallback}
function badgeClass(v:string){if(['P0','失败','阻塞','不能上线','已驳回'].includes(v))return'red';if(['P1','待审核','待补充','有条件上线','未执行'].includes(v))return'yellow';if(['通过','已完成','已发布','审核通过','已入库','可上线','启用','可创建'].includes(v))return'green';if(['执行中','项目'].includes(v))return'blue';return'gray'}
function shortModule(label:string){return label?.split(' / ').slice(-2).join(' / ')||'未指定'}
function moduleFromId(id:string){const map:Row={mod_pay_callback:'支付中心 / 支付回调',mod_pay_order:'支付中心 / 订单同步',mod_order_coupon:'订单中心 / 优惠券'};return map[id]||id}
function date(v:string){return v?new Date(v).toLocaleDateString('zh-CN',{year:'numeric',month:'2-digit',day:'2-digit'}).replaceAll('/','-'):'—'}
function dateTime(v:string){return v?new Date(v).toLocaleString('zh-CN',{hour12:false}):'—'}
function pretty(v:any){if(typeof v==='string')return v;return Object.entries(v||{}).map(([k,val])=>`${k}：${Array.isArray(val)?val.join('；'):typeof val==='object'?JSON.stringify(val):val}`).join('\n')}
function groupBy(items:Row[],key:string){return items.reduce((a:Row,x:Row)=>((a[x[key]]||=[]).push(x),a),{})}
function groupModules(modules:Row[],cases:Row[]){const out:Row={};for(const m of modules){const rows=cases.filter(c=>c.moduleId===m.id);if(!rows.length)continue;out[m.projectName]??={};out[m.projectName][m.moduleName]??={};out[m.projectName][m.moduleName][m.submoduleName]=rows;}return out}
function countTree(v:any):number{return Array.isArray(v)?v.length:Object.values(v||{}).reduce((n:any,x:any)=>n+countTree(x),0) as number}
function downloadRows(rows:Row[],name:string,format:string){if(format==='xlsx'){const ws=XLSX.utils.json_to_sheet(rows),wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'数据');XLSX.writeFile(wb,`${name}.xlsx`);return}const text=format==='json'?JSON.stringify(rows,null,2):XLSX.utils.sheet_to_csv(XLSX.utils.json_to_sheet(rows));downloadText(text,`${name}.${format}`)}
function downloadText(text:string,name:string){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
function regressionText(r:Row){return `# ${r.title}\n版本：${r.data.version}\n进度：${r.progress}%\n\n${r.data.items.map((x:Row)=>`- [${x.status==='通过'?'x':' '}] ${x.priority} ${x.title}｜${x.status}`).join('\n')}`}
function exportRegression(r:Row,notify:any){if(!r)return;downloadRows(r.data.items.map((x:Row)=>({优先级:x.priority,回归项:x.title,模块:moduleFromId(x.moduleId),状态:x.status,预期:x.expected,实际:x.actual,负责人:x.owner})),r.title,'xlsx');notify('回归清单已下载')}
function reportMarkdown(r:Row){return `# ${r.title}\n\n- 报告日期：${date(r.createdAt)}\n- 项目：${r.projectName}\n- 版本：${r.version}\n- 上线结论：${r.verdict}\n- 覆盖模块：${(r.data.modules||[]).join('、')}\n\n## 执行结果\n\n通过 ${r.data.passed||0}，失败 ${r.data.failed||0}，阻塞 ${r.data.blocked||0}。\n\n## 风险与遗留问题\n\n${(r.data.risks||['无']).map((x:string)=>`- ${x}`).join('\n')}`}
async function downloadPdf(r:Row){const page=document.createElement('div');page.style.cssText='width:720px;padding:42px;background:white;color:#1d1f1c;font-family:Noto Sans SC,Arial;line-height:1.8';page.innerHTML=`<h1>${r.title}</h1><p>报告日期：${date(r.createdAt)}　项目：${r.projectName}　版本：${r.version}</p><h2>上线结论：${r.verdict}</h2><p>覆盖模块：${(r.data.modules||[]).join('、')}</p><h2>执行结果</h2><p>通过 ${r.data.passed||0}，失败 ${r.data.failed||0}，阻塞 ${r.data.blocked||0}。</p><h2>风险与遗留问题</h2><ul>${(r.data.risks||['无']).map((x:string)=>`<li>${x}</li>`).join('')}</ul>`;document.body.appendChild(page);const doc=new jsPDF({unit:'px',format:'a4'});await doc.html(page,{margin:[24,24,24,24],autoPaging:'text',width:398,windowWidth:720});doc.save(`${r.title}.pdf`);page.remove()}

createRoot(document.getElementById('app')!).render(<React.StrictMode><App/></React.StrictMode>);
